### ISSUE TITLE
Export / Download doesn't work

### ISSUE THREAD

**Issue by konstin** [pawelrojek/nextcloud-drawio#1]
When I try to export a file and then download it, nothing happens. Ideally, an exported image should be stored in the same folder as the original xml file.

Otherwise, it's a great add-on!

**Comment by konstin** [comment]
It's fixed in 0.8.6, thanks!

**Comment by pawelrojek** [comment]
Fixed in v0.8.6.

As for exporting image to the same folder, I will try to include it in the next release. 
It's just not that straightforward and simple. Draw.io has some limitations, but I have some ideas for a workaround, so it's not a lost cause :)

**Comment by geiseri** [comment]
In theory you can have a button on the top bar to invoke the "export" command.  I would argue that the draw.io guys need to fix it to act more like the save function.
