### ISSUE TITLE
Draw.io could not be enabled in NC12

### ISSUE THREAD

**Issue by xaerox666** [pawelrojek/nextcloud-drawio#10]
After upgrade to NC12 and Draw.io app to version 0.8.7 it is not possible to enable app in apps menu:

![image](https://cloud.githubusercontent.com/assets/28889186/26343556/bc35fbb6-3f9c-11e7-8ef2-f8a173f95b86.png)

**Comment by acidhunter** [comment]
i did a pull request about this issue

#11

**Comment by acidhunter** [comment]
https://github.com/pawelrojek/nextcloud-drawio/pull/11/files#diff-3dd822b3ce788a2f9b9af27f79f7e8d8
