### ISSUE TITLE
Compatibility with Nextcloud 18

### ISSUE THREAD

**Issue by azmelanar** [pawelrojek/nextcloud-drawio#101]
Please add support for Nextcloud 18 (https://github.com/nextcloud/server/releases/tag/v18.0.0)

**Comment by pawelrojek** [comment]
I was planning to do it last Friday, but for some reason I can't even update my test instances. I've got "Your version is up to date" on both release channels (stable & beta). And it still doesn't work (as of today). Unfortunately, I didn't and still don't have time for a manual update.

**Comment by q-wertz** [comment]
For me the update worked today after setting channel to beta.

**Comment by e-alfred** [comment]
Nextcloud 18.0.1 is out now, it would be great to have this app released for Nextcloud 18 too.

**Comment by davidjgraph** [comment]
Trust me, Pawel, you'll learn to hate open source and its users :D.

**Comment by e-alfred** [comment]
@davidjgraph Sad to hear that you think about it like that. I also maintain a few Nextcloud apps and yes, the very rapid release cycle makes it difficult to keep up for both the users and app developers alike. But making a release is not something others can fix with a PR but relies on the person publishing the app to the App Store so users are dependent on it.

**Comment by davidjgraph** [comment]
Wait till you've been doing it for 20 years :). But this is off-topic, off-topic comments are bad, feel free to delete.

**Comment by wizdude** [comment]
i'm a draw.io fan and i have enjoyed the integration with nextcloud for storage of my files. +1 support for Nextcloud 18 as well :-)

**Comment by BloodyIron** [comment]
Feb 19th, really would like this to be compatible with NC18! Please? :)

**Comment by pawelrojek** [comment]
I can't release it without testing it. 

Sadly, I couldn't easily update my test instances. It just didn't work (without any errors or warnings). I spent like 3 hours studying logs, tinkering etc. trying to figure out why the updater doesn't work. I ended up with a malformed XML (the response for the "update URL"). I gave up...

Another step was a Manual Update. And this is how I finally figured out the problem. PHP 7.1, which I was using, is no longer supported. But PHP 7.1 was listed as a supported version when 18.0 came out (not "recommended" but "supported") - I remember checking the requirements.

Right now I'm in the process of installing another instance of PHP (7.3) on my test server. I can't just update and replace it, so it's not that simple.

Sometimes it takes a lot of work (long hours) to test it and release it.
It's a free, open-source project. Have patience.

**Comment by BloodyIron** [comment]
Your hard work is apprecited! Thanks! :D

**Comment by plinss** [comment]
@pawelrojek If you need a test instance I have a dev server I can give you access to. Debian Buster, PHP 7.3. Drop me an email github&lt;at>linss&lt;dot>com.

**Comment by e-alfred** [comment]
@pawelrojek Sad to hear that you have some serious problems updating to Nextcloud 18. If you need some help testing out the app on Nextcloud, just tell me what to look after and I will test it on my instance.

**Comment by pawelrojek** [comment]
It's finally out! :) 🍾

**Comment by BloodyIron** [comment]
WOOT! :DDD

**Comment by BloodyIron** [comment]
Hmmm don't see the update available just yet. How long does that take to process?

**Comment by pawelrojek** [comment]
I have no idea, but it's listed as NC18 compatible here:
https://apps.nextcloud.com/apps/drawio

**Comment by BloodyIron** [comment]
Ahh showing up now!

**Comment by wizdude** [comment]
thanks @pawelrojek you are the best!

**Comment by azmelanar** [comment]
thanks @pawelrojek
