### ISSUE TITLE
URL local/own draw.io server?

### ISSUE THREAD

**Issue by goforgit** [pawelrojek/nextcloud-drawio#103]
Hello
First of all! Thank's for this great nextcloud app.
Does the app support privat domains like http://drawio.localhost? I have setup a draw.io server using the draw.war (https://github.com/jgraph/drawio/releases; v 12.7.2) file one can find on github. Then I set up an http apache2 vhost and created an local DNS record in openwrt/dnsmasq. I can reach the local draw.io using http://drawio.localhost in my Browsers (Chromium, Firefox). But when I use this url in the nextcloud draw.io admin settings, I get a blank page. Go I back to the url https://www.draw.io everthing work as expected.

Does the app support privat domains like http://drawio.localhost?

Kind regards, go4git

**Comment by pawelrojek** [comment]
Yes, it does support private instances.

Go to Settings -> Administration -> Additional Settings( /index.php/settings/admin/additional )
and there's the "Draw.io URL" setting, which you can change to your own URL.
