### ISSUE TITLE
redirect to NC home page if filename contains "+"

### ISSUE THREAD

**Issue by iWangJiaxiang** [pawelrojek/nextcloud-drawio#108]
Hi, I found a bug.

Just create a diagram file with `+` in the filename. And the online drawio editor will always redirect to NC home page. So there is no chance to edit the file with `+` in file name.

Env:

Nextcloud 18.0
drawio plugin 0.9.5

**Comment by Ali-romdhani** [comment]
Same here with the `"` symbol. Nextcloud display a blank page with no indication.

Nextcloud 18.0.3
DrawIo plugin : 0.9.5

**Comment by pawelrojek** [comment]
Will be fixed in the next release.
