### ISSUE TITLE
Problematic mapping to XML file extension

### ISSUE THREAD

**Issue by despens** [pawelrojek/nextcloud-drawio#114]
Drawio is feeling responsible for every file with an `xml` extension on my nextcloud. Since I am working with a bunch of project specific xml files this can cause confusion, especially with collaborators.

Perhaps another file extension could be chosen, like `dxml` or similar, to clearly distinguish what files drawio is handling.

**Comment by MrMid** [comment]
Draw.io exports files with extension `drawio`. So I would suggest using that.

**Comment by Entrio** [comment]
What about the old xml files? My drawio after todays update stopped opening all of the files that are XML format
