### ISSUE TITLE
Requests to the server have been blocked by an extension.

### ISSUE THREAD

**Issue by yagikaroo** [pawelrojek/nextcloud-drawio#118]
Update to [NextCloud] 19.0.1 and now draw.io will not load at all. It will give the message

Requests to the server have been blocked by an extension.

This is on Edge 84.0.522.40, and on Firefox it will just not load a page or errors.

**Comment by davidjgraph** [comment]
Is that using the draw.io online site or your own hosted draw.io?

**Comment by yagikaroo** [comment]
This is using draw.io, I setup a docker with a draw.io instance and it also did not load. I don't know if I have to configure the instance to work with it though.

**Comment by davidjgraph** [comment]
We started redirecting draw.io today. What's the URL it's trying to access and is it getting redirected?

**Comment by yagikaroo** [comment]
the url that is default in the nextcloud app is https://www.draw.io, in the web browser it will redirect to https://app.diagrams.net/

after this I put this in as the server and it is working! Thanks, simple fix today!!

**Comment by yagikaroo** [comment]
Well, I guess I need to focus my eyes more or get glasses because it will open in the https://app.diagrams.net/ interface and not stay in the nextcloud interface

**Comment by yagikaroo** [comment]
Idk if this should be closed yet, leaving open for now.

**Comment by MelpodPixel** [comment]
Thank you for that hints. I could follow your recommendation and changed the file appconfig.php.
But in addition, I received the comment, that https://app.diagrams.net/ should be avoided.
I changed to https://embed.diagrams.net/ and now draw.io in Nextcloud is working fine again.

**Comment by mfbatra** [comment]
Hi @yagikaroo , I am facing the same issue. Can you please guide how i can make the changes to make it work again?

**Comment by yagikaroo** [comment]
@MelpodPixel Yes after a while i noticed that too! I guess I need some glasses and to slow down and read the UI. 

@mfbatra All you need to do is go to Settings in NextCloud, then Additional Settings on the left hand menu, then under the Draw.io section change the  "Draw.io URL" box to be `https://embed.diagrams.net/`

**Comment by Bergum** [comment]
I have this same problem on Nextcloud 18.0.7

Refused to frame 'https://app.diagrams.net/' because it violates the following Content Security Policy directive: "frame-src https://www.draw.io blob:".

Worked yesterday, not today.

**Comment by davidjgraph** [comment]
We've switched the redirection off for now. Once your browser stops trying to follow the redirect, it'll go back to how it was.

**Comment by Bergum** [comment]
That solved my problem.
Vorks great again.
Thank you.

**Comment by davidjgraph** [comment]
To tidy up, we would be looking to set the redirect back at some point, but I suspect we'll need to wait 1-2 years for enough people to move to the next version that sets the URL to the new value.

**Comment by pawelrojek** [comment]
The new version (0.9.7), which was released today (~12 hours ago), will automatically replace http(s)://(www.)draw.io with https://embed.diagrams.net . That should help.

**Comment by Bergum** [comment]
The new version worked for me.
