### ISSUE TITLE
Viewer no longer works - Page Could Not Be Loaded. Please Try Refreshing.

### ISSUE THREAD

**Issue by linucksrox** [pawelrojek/nextcloud-drawio#121]
Page could not be loaded. Please try refreshing.
Please ensure JavaScript is enabled.

Version 0.9.7 of the draw.io app, Nextcloud 19.0.1 and Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

This message occurs when attempting to open an old document (created over a year ago), a new document (created 6 days ago), or even creating a brand new document.

Console errors of interest are:
```
app.min.js:10076 Uncaught TypeError: Cannot read property 'getItem' of null
    at Object.load (app.min.js:10076)
    at app.min.js:10080
load @ app.min.js:10076
(anonymous) @ app.min.js:10080
?embed=1&offline=1&stealth=1&ui=kennedy&lang=en&spin=1&proto=json:421 Uncaught ReferenceError: App is not defined
    at ?embed=1&offline=1&stealth=1&ui=kennedy&lang=en&spin=1&proto=json:421
(anonymous) @ ?embed=1&offline=1&stealth=1&ui=kennedy&lang=en&spin=1&proto=json:421
```

**Comment by twenster** [comment]
I also have the same issue on Nextcloud 18.0.7. No draw.io or Nextcloud extension (old or newly created) can be opened.

**Comment by ShadowJonathan** [comment]
I also have the same problem

**Comment by ShadowJonathan** [comment]
@twenster @linucksrox it seems that disabling ad-blocking extensions fixes this, on brave browser this means "lowering the shields"

**Comment by linucksrox** [comment]
I had tried that previously, but it didn't help. I'm not sure what changed, but obviously it was something on the client side with caching or something else. It's working fine for me now.
