### ISSUE TITLE
Last updates breaks nextcloud admin

### ISSUE THREAD

**Issue by loxK** [pawelrojek/nextcloud-drawio#13]
I just updated to 0.8.8 on Nextcloud 12. **Without activating it**.

Accessing /settings/admin throws an internal error.

In the logs I have:

`"app":"index","method":"GET","url":"\/nextcloud\/settings\/admin","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/srv\\\/www\\\/nextcloud\\\/apps.installed\\\/drawio\\\/lib\\\/adminsettings.php\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/srv\\\/www\\\/nextcl...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#3 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(94): ReflectionClass->__construct('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#4 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#5 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#6 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(261): OC\\\\ServerContainer->query('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#7 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(352): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Drawio\\\\\\\\Admi...')\\n#8 \\\/srv\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(138): OC\\\\Settings\\\\Manager->getAdminSettings('server')\\n#9 \\\/srv\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(72): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('server')\\n#10 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('server')\\n#11 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#12 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#13 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#14 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#17 \\\/srv\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#18 \\\/srv\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/srv\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php\",\"Line\":134}"`

If activated there is no issue.

**Comment by Noneatme** [comment]
Can confirm, same error when disabling the drawio app.

**Comment by chuckf** [comment]
This is also an issue when upgrading from 11.0.2 to 11.0.3.

**Comment by e-alfred** [comment]
@Noneatme Direct menu app is deprecated for NC 12, because the features were integrated into the core.

https://apps.nextcloud.com/apps/direct_menu

**Comment by tgroman** [comment]
I can confirm this bug.
Updated this app while it was disabled. got the following error.

OCP\AutoloadNotAllowedException: Autoload path not allowed: /var/www/nextcloud/apps/drawio/lib/adminsettings.php
Locked out of admin interface even though DrawIO was disabled until DrawIO was uninstalled

Nextcloud 11.0.3
DrawIO 0.8.8

**Comment by pawelrojek** [comment]
Added to "Known Issues".

I can't replicate it :) Happens sometime.
