### ISSUE TITLE
Errors on public shared Links

### ISSUE THREAD

**Issue by BlockMen** [pawelrojek/nextcloud-drawio#133]
First, thanks for your work on this app, its great!

Testing on commit c02cebbe37dfd5a424e017e499a2215ed3fdce5a here my findings:
- Option to open a shared file with Draw.io is only shown when disabling the builtin "text" App (even with mimetypes in config folder)
- Even then it doesn't work yet, giving an internal server error, with following server logs:
`index | Exception: Call to a member function getRelativePath() on null`
`Error: Undefined variable: baseFolder at /var/www/nextcloud/apps/drawio/controller/editorcontroller.php#174`

Unfortunately i don't know any of the nextcloud API so i just wildguessingly changed L174 to `"drawioFilePath" => rawurlencode($relativePath),` which indeed fixed (?) the issue mentioned above, but does not load the file. Instead an error from draw.io is given: `Fehler Keine Diagrammdatei` which translates to `no diagram file found`

I hope this helps solving the issues as i would love to use Draw.io with shared files :)

Cheers,
BlockMen

**Comment by BlockMen** [comment]
Sry, but #136 does NOT fix my issue. As stated above after applying the correct path variable the public shared file is still not opening:

` Instead an error from draw.io is given: Fehler Keine Diagrammdatei which translates to no diagram file found`

**Comment by kilbith** [comment]
@BlockMen Eat that, motherfucker:

![Scuba_Lights](https://user-images.githubusercontent.com/7883281/122658777-7c309380-d171-11eb-993b-781d07ffc3ad.png)

This is in Minetest now. Have fun with your fork.
