### ISSUE TITLE
Release 0.9.9 broke Nextcloud

### ISSUE THREAD

**Issue by mhaluska** [pawelrojek/nextcloud-drawio#138]
Latest release is blocking basic operations (for example + sign to create new file - totally blocked, no menu appears) and drawio mime is not working. Only Brave browser is working.

OS client: macOS 11.2.2, Windows Server 2019
Browser: tested -  Safari and Firefox = problem, Brave = OK
Nextcloud: 21.0.0
Drawio app: 0.9.9
OS server: Debian 10
Web server: nginx 1.14.2
PHP: 7.3.27

When I disable Drawio app, everything is again working.

Edit: Also Brave stopped working, probably some files has been cached.

**Comment by JoshuaPettus** [comment]
I bet you this is related to my ticket #137

**Comment by mhaluska** [comment]
@JoshuaPettus seems you was quicker than me, except I don't see such error in log. Are you experiencing same issues like me? App doesn't open, just offers file download (like missing MIME).

**Comment by JoshuaPettus** [comment]
Yeah,  after the app crashes, draw.io is disabled by nextcloud and MIME resets to default for .xml

**Comment by mhaluska** [comment]
Thanks for info, seems this is same issue, not related to PHP version.

**Comment by harry-t-itch** [comment]
I have the same issue. did some research on the erroro report in the log and tried the solution here: https://github.com/nextcloud/server/issues/24711#issuecomment-785198651
No success so far. I had to deactivate draw.io for "+"-menu to work again.

**Comment by pawelrojek** [comment]
It seems to freeze after you exit an opened file and return to the NC (sometimes, but not always). 

As a temporary workaround you can try reloading the page with CTRL+F5.

I'm working on a proper solution.

[btw - console log is flooded with warnings and deprecation notices]

**Comment by mhaluska** [comment]
CTRL+F5 didn't work for me. Even using incognito with clean cache = (+)-menu is blocked when Drawio app is active.

**Comment by harry-t-itch** [comment]
Same here. There is actually a difference between using firefox and chrome. While in firefox it doesn't work at all (filetype not registered, "+"-menu Not working), when drawio is active, in chrome it is possible to open a drawing after activation just once. Afterwards the filetype seems to be not registred anymore (just plaintext when opening it, and no logo associated) and the "+"-menu doesn't work. hope this helps.

**Comment by pawelrojek** [comment]
It should work now. Tested on PHP 8.0 / 7.3 - NC21 and NC20.

**Comment by mhaluska** [comment]
Tested on two instances (NC21), works without problem. Thank you

**Comment by harry-t-itch** [comment]
> 
> 
> It should work now. Tested on PHP 8.0 / 7.3 - NC21 and NC20.

fix confirmed on NC21 (docker). thanks a lot!
