### ISSUE TITLE
Problem opening .drawio file from nextcloud 

### ISSUE THREAD

**Issue by Hitman062** [pawelrojek/nextcloud-drawio#145]
hello, since the last update (1.0.0) I can't open the .drawio files (previously .xml that was renamed as indicated in the changes), it just downloads them, even though it creates new ones, when saving and closing I can't reopen them

**Comment by pawelrojek** [comment]
Go to Admin settings > Additional settings ( /index.php/settings/admin/additional ) and click the Save button to register MIME types.

**Comment by Hitman062** [comment]
> Go to Admin settings > Additional settings ( /index.php/settings/admin/additional ) and click the Save button to register MIME types.

Excellent, thank you very much, now it works perfectly

**Comment by jcjc86** [comment]
It works for only the files already created, but no for the new files, you need to claci again the save botton if you want to make the files accesible on the browser. This is going to be fixed?
