### ISSUE TITLE
draw.io / diagrams.net does not open in nextcloud anymore

### ISSUE THREAD

**Issue by jjanarnava** [pawelrojek/nextcloud-drawio#149]
drawio 1.0 Plugin 

I have several diagrams created with th plugin, the filename is filename.drawio within nextcloud 20, for a week or so I get only a download dialogue clicking in the web interface at the file, the editor does not open any more. Any suggestions?

yes i cna download the file and open it at https://app.diagrams.net/ edit and download to check in again, but that is too difficult for most users...

Kind Regards 
Bert

**Comment by pawelrojek** [comment]
Go to Admin settings > Additional settings ( /index.php/settings/admin/additional ) and click the Save button to register MIME types.

If this doesn't work, check this issue: https://github.com/pawelrojek/nextcloud-drawio/issues/148

**Comment by jjanarnava** [comment]
Thank You. It worked!
Kind regards | Herzlichst
Organisational and Human Development

Bert Zimpel

FON +49 1575 2097620
Expert Fellow and Member of the Cooperative
of the "Akademie für Potentialentfaltung"

23.05.2021 22:00:25 Paweł Rojek ***@***.***>:
