### ISSUE TITLE
[Question] use without internet access?

### ISSUE THREAD

**Issue by sthag** [pawelrojek/nextcloud-drawio#15]
Does nextcloud-drawio need internet access?
What exactly does the setting Draw.io URL do?

We have a Nextcloud within a private network. It is only allowed internet access for updates.
Is it possible to use drawio so it does not connect to internet on the client browser side?
I guess the URL option has something to do with this.

**Comment by sthag** [comment]
I found some information about self-hosting draw.io on the [GitHub wiki](https://github.com/jgraph/draw.io/wiki/Building).
If the nextcloud providing drawio is already locally hosted, could it be an option to also have drawio completely local?

**Comment by poVoq** [comment]
Easily possible, explained here:
https://github.com/pawelrojek/nextcloud-drawio/issues/2

Just download the source code of draw.io, then take the /war/ directory out of that and put it into your webserver (optionally rename it to "drawio" or something like that), the adapt the URL in the Nextcloud settings to yourdomain/war/ or whatever you named the directory.

**Comment by sthag** [comment]
Thanks for the link. I missed this issue.
