### ISSUE TITLE
Nextcloud 23

### ISSUE THREAD

**Issue by Derkades** [pawelrojek/nextcloud-drawio#167]
Issue for tracking Nextcloud 23 compatibility

**Comment by arnowelzel** [comment]
Works without any issue here so far. I use it in "offline mode" and with my own Draw.io instance in a Docker container

**Comment by pawelrojek** [comment]
I'm gonna test it and release the new version today.


PS. Sorry for the complete lack of activity here. I'm always busy, but the last three months were next level busy for me :)

**Comment by daSubby** [comment]
No Problem. Thanks for your effort.
