### ISSUE TITLE
nextcloud 13

### ISSUE THREAD

**Issue by prilly** [pawelrojek/nextcloud-drawio#25]
Is this app tested on nextcloud 13?

**Comment by Laupe** [comment]
@pawelrojek  Waiting for NextCloud 13 support! Pls

**Comment by DBJRdev** [comment]
Please make it available for Nextcloud 13; that would be wonderful. Thanks for the effort!

**Comment by TigerDK** [comment]
Second this, 13 is getting nearer. It's already in RC

**Comment by cayetano** [comment]
NextCloud 13 is stable..... Please !!!!!!!
This is a wonderful tool !!!

**Comment by tsueri** [comment]
I think the new app will be published soon: https://github.com/pawelrojek/nextcloud-drawio/pull/24

**Comment by toms1342** [comment]
Please make this wunderful app work wit "NC13 stable" again.

**Comment by pawelrojek** [comment]
I'm gonna try to find some time to test it, and release it soon.

**Comment by TigerDK** [comment]
I have manually added the changes into the app and can confirm it works well on my end. I haven't run into any issues as of yet.

**Comment by toms1342** [comment]
I made the same experience like TigerDK. No issues until now. fantastic job, well done! 
A tiny, very small bug:
The language can't be changed on user level. System-wide, no problem. Solving this would be three extra stars for your work :) 
Thank you so much for this app.

**Comment by mracreep** [comment]
Im still missing it in Nextcloud 13 Stable... Is that correct?

**Comment by makeITpossible001** [comment]
@TigerDK What changes have you made in the app? Thank you very much

**Comment by makeITpossible001** [comment]
Thank you! Have made the changes for NC13 also manually. Everything perfect.
[](https://github.com/pawelrojek/nextcloud-drawio/commit/4e2f117bd026cf9c7f093df1479d5ec27594a8e8)

**Comment by nicolass67** [comment]
Hello all, 
Can someone eventually post the "manual" modifications to make it work on NC 13 ? 
Or is it better to wait a few days more if it's planned that draw.io comes again on NC13 ? :)

Thanks and regards,

**Comment by makeITpossible001** [comment]
@nicolass67 https://github.com/makeITpossible001/nextcloud-drawio/commit/4e2f117bd026cf9c7f093df1479d5ec27594a8e8
Best mitp

**Comment by tomkiv897** [comment]
Are there any plans to officially support Nextcloud 13? The app is not available in the market.

**Comment by 11111000000** [comment]
When?

**Comment by shieldwed** [comment]
I have manually upgraded the app as well. It works so far.

**Comment by mikess** [comment]
YOU BASTARD! Everything is working fine. Just clone drowio/drowio directory to ${NEXTCLOUD}/apps/ and enable it ;)

**Comment by pawelrojek** [comment]
Released.
🍾 🍾 🍾

https://apps.nextcloud.com/apps/drawio

Sorry for the delay, folks. It really takes a lot of time to maintain, test, check, pack, sign, publish. And nobody's paying me a dime so relax.

**Comment by mikess** [comment]
@pawelrojek daj nr konta to wyśle Ci na flaszkę ;)

**Comment by madmath03** [comment]
@pawelrojek Thanks a lot! We do realize that it takes time, we just love the Draw.io integration so much we were impatient to see it again ;)

**Comment by nicolass67** [comment]
@pawelrojek : Thanks for this great job !
