### ISSUE TITLE
Move app data to the root directory

### ISSUE THREAD

**Issue by juliushaertl** [pawelrojek/nextcloud-drawio#3]
That will make it easier to start developing or running the latest version from git.
You can then just clone the repo directly to your Nextclouds app folder.

**Comment by pawelrojek** [comment]
I guess you can use symlinks or something like that.

The way things are right now you can just copy "drawio" directory to /apps/ and I also think it's better to keep it for compatibility reasons and clarity ("screenshots" directory etc.).
