### ISSUE TITLE
Use custom file type for diagrams instead of ".xml"

### ISSUE THREAD

**Issue by arnowelzel** [pawelrojek/nextcloud-drawio#32]
As of version 0.89 Draw.io uses the extension ".xml". There is also an option to connect ".xml" with Draw.io.

However - since ".xml" is a very generic extension and Draw.io itself does not require to use this extension, it would be nice to have a more specific file type - e.g. ".drawio" and "application/x-drawio" as MIME type, so not all XML files get treated as diagram but you still can open diagrams with a simple click on the file. Also see Collabora which automatically opens files with the extensions ".odt", ".ods", ".docx", ".xlsx" etc..

BTW: how can a Nextcloud application can register it's own file types?

**Comment by PhilsLab** [comment]
+1

**Comment by cuthulino** [comment]
+1

**Comment by arnowelzel** [comment]
My pull request was still not merged - so I'm not sure, if there is a problem with it. However this change works in my own server without problems since I patched it this way.

**Comment by arnowelzel** [comment]
The change got merged :-). pawelrojekt just didn't notice the pull request.
