### ISSUE TITLE
Problem Nextcloud 13 and Firefox 59

### ISSUE THREAD

**Issue by ybarmax** [pawelrojek/nextcloud-drawio#33]
Hello, I test te app in IE and work fine, in the last version of firefox, opera, not working. some help please.
thanks.

**Comment by arnowelzel** [comment]
Just tested it with Firefox 59 x64 in Windows 10 Pro - no problems at all.

Does Draw.io generally work? See [https://www.draw.io/](https://www.draw.io). Maybe you should also try a new profile in Firefox, just to be sure that no Addons interfere with it (see [https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)

**Comment by xlyz** [comment]
firefox 59.0.2 working fine here as well
