### ISSUE TITLE
Settings part is doubled

### ISSUE THREAD

**Issue by lachmanfrantisek** [pawelrojek/nextcloud-drawio#4]
Thank you for such a nice app.

I found a minor bug in settings. I see the `draw.io` part both in `admin` (settings root) as well as in `admin/additional`.

-----

### Server configuration
**Operating system**: Linux 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64

**Web server:** nginx/1.13.0 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (Alpine 6.2.1) 6.2.1 20160822, 64-bit

**PHP version:** 7.1.4
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, ftp, gmp, intl, ldap, mcrypt, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 11.0.3 (daily) Build:2017-05-01T21:01:27+00:00 398013b1a5827818e5fa4f55b574f8d85b95f00a - 11.0.3.2

**Are you using encryption:** no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:** Fedora Rawhide

**Comment by awesome-manuel** [comment]
Actually the settings should be neither in admin nor in admin/additional. Instead a separate entry admin/drawio should be created like for the Talk app.

**Comment by lachmanfrantisek** [comment]
@xlyz @awesome-manuel Thanks for resolving the issue!
