### ISSUE TITLE
Error in en_GB.json missing comma

### ISSUE THREAD

**Issue by Gatak** [pawelrojek/nextcloud-drawio#44]
Row. 32 "You do not have enough permissions ..." should end with a comma. It doesn't and that cause "json error code 4" in the logs.

**Comment by aljawaid** [comment]
I have the same issue

| Level    | App  | Message                                                                                        |
|----------|------|------------------------------------------------------------------------------------------------|
| Warning  | l10n | Failed to load /home/domain/public_html/cloud/apps/drawio/l10n/en_GB.json - json error code: 4 |

**Comment by aljawaid** [comment]
@pawelrojek any way of fixing this?

**Comment by aljawaid** [comment]
#55
