### ISSUE TITLE
Draw.io not available on Nextcloud 14

### ISSUE THREAD

**Issue by PeterWilliams360** [pawelrojek/nextcloud-drawio#54]
Hi,
I would like to install Draw.io on Nextcloud 14, but this app isn't available on official store https://apps.nextcloud.com/apps/drawio

Nextcloud 14 stable was released on 2018-Sep-06. How could I get Draw.io available for Nextcloud 14?
Thanks in advance.

**Comment by victorarocha** [comment]
Same here. Please make available a nextcloud 14 version ! Thanks in advance.

**Comment by aproposnix** [comment]
Releated to: 

- Compatibility with Nextcloud 14 #47 
- Pull Request: Add Nextcloud 14 compatibility #53

**Comment by Huster-at-github** [comment]
App for NC 14.0.1 still not available.

**Comment by pawelrojek** [comment]
I'm working on it. 

I can't even see it in Auto-Updater yet (Stable/Production channels). It's only available in the "Beta channel" for now (at least for me). And while updating using Beta channel I've ended up with some "500 Internal Server" errors I need to handle first.

Anyway, I'm planning to release it by the end of the week.

**Comment by Poirux-TheLeekman** [comment]
Yeah!!! What a good news!!! 😁
Thank you so

Le mar. 25 sept. 2018 à 17:42, Paweł Rojek <notifications@github.com> a
écrit :

**Comment by e-alfred** [comment]
Nextcloud 12 will be officially supported until November. The old release still works with 12, you could simply limit the new version to 13-14 and upwards?

**Comment by pawelrojek** [comment]
Update:
I've finished setting up a new testing environment. Now I've got all the versions installed side-by-side with PHP 5.6 and 7.2. It had to be done sooner or later, NC14 is the second major version in less than a year...

Release is pushed to Tuesday.
