### ISSUE TITLE
Where are the uploaded images getting stored ?

### ISSUE THREAD

**Issue by mantri-govind** [pawelrojek/nextcloud-drawio#67]
Hi

Here is my scenario:

- I have self hosted  Nextcloud instance running behind firewall (obviously no access to internet at all)
- I have hosted version of Draw.io (again running behind the same firewall)
- While creating a diagram I have uploaded one of the image from my system, and saved the diagram

Queries/Concerns : 

- Where does this uploaded image got saved ?
- When I export this diagram as xml or whatever format and upload that xml on public draw.io, how it manage to pull down the same image, does that mean whatever we upload to nextcloud draw.io is getting uploaded to public draw.io ?
- Although in exported xml you won't be able to find reference to any image file, may be xml would have been encrypted, but still why would the same xml (which have private upload) will work on other drawio server.

I hope I'm able to explain my concern coz if it uploading on public draw.io instance or somewhere else on public network.. its a serious security and information leak..

Thanks

**Comment by janLo** [comment]
Nothing gets uploaded anywhere. 

The included images are stored (base54-encoded) in the drawio-file itself. This also explains why the file can be loaded without missing images on any instance.

The contents of your diagram are also not encrypted. They're just compressed in the drawio file. This is done [here](https://github.com/jgraph/drawio/blob/2d6ce4910c8c175d6746efd0ca8f2fd1ba687678/src/main/webapp/js/mxgraph/Graph.js#L2969-L2999).

You can view the contents of the drawio-file be decompressing the textblock in the <diagram/> node in your saved file. This script for example will do:
```python
#!/usr/bin/env python3                  
                                        
import base64                           
import sys                              
import zlib                             
                                        
from urllib.parse import unquote        
import xml.etree.ElementTree as ET      
                                        
                                        
if __name__ == "__main__":              
    if len(sys.argv) < 2:               
        print("Usage: " + sys.argv[0] + " <diagram>")
                                        
    envelope = ET.parse(sys.argv[1])    
    content = envelope.find("//diagram").text
    compressed = base64.b64decode(content)
    quoted = zlib.decompress(compressed, wbits=-15)
    plain = unquote(quoted.decode("utf-8"))
                                        
    print(plain)
```

There you should see for your imported image something like:
```xml
...<mxCell id="5" value="" style="shape=image;imageAspect=0;aspect=fixed;verticalLabelPosition=bottom;verticalAlign=top;image=data:image/png, ... base64 encoded image data ... ;" vertex="1" parent="1"><mxGeometry x="340" y="340" width="352" height="520" as="geometry"/></mxCell>
```

**Comment by mantri-govind** [comment]
Thanks @janLo for detailed clarification.
