### ISSUE TITLE
Draw.io does not work with Nextcloud 15.0.0. :...(

### ISSUE THREAD

**Issue by Manfredzimmermann** [pawelrojek/nextcloud-drawio#68]
I'm totally desperate. :(

I did update my Nextcloud to 15.0.0. Now it does not work anymore with Draw.io. What do I have to do to make Draw.io work again?

Please help me. Thank you.

**Comment by fintara** [comment]
It seems fixed in #66, but perhaps a new version should be released.

**Comment by Manfredzimmermann** [comment]
My Nextcloud is running at a service provider. I only have access to the web interface of Nextcloud. I can  update Draw.io only on Webinterface with a button. When will the latest version of Draw.io for Nextcloud be released?

**Comment by pawelrojek** [comment]
Done :)

**Comment by Manfredzimmermann** [comment]
You are super. It works now. :)

Thank you very much.
