### ISSUE TITLE
Autosave xml

### ISSUE THREAD

**Issue by kcepaxe** [pawelrojek/nextcloud-drawio#75]
Please, add autosave function in admin panel. Users work in draw.io many hours without save file, sometimes browser crash and all they data lost. I dont know why users do that, but they do.

**Comment by JortdeBokx** [comment]
Would love to see this. Had many similar issues with data being lost

**Comment by kyhuynhduc** [comment]
this funtion is awesome. we love to see it.

**Comment by BloodyIron** [comment]
Using it now, really do need auto save D:

**Comment by putt1ck** [comment]
Is there a way to add bounties for this?

**Comment by pawelrojek** [comment]
Added in 0.9.6.

**Comment by BloodyIron** [comment]
Woot! Looking forward to it trickling down to the repos :D
