### ISSUE TITLE
Nextcloud Integration Issue (page does not load)

### ISSUE THREAD

**Issue by mbelton** [pawelrojek/nextcloud-drawio#9]
My company created a server for draw so we could integrate it with our Nextcloud instance.

The application loads great when you connect directly but the issue is when trying to open a saved .xml file from Nextcloud.

Once you click the icon for the file, a tab opens and the page only loads the banner with all options grayed out except File and Help. The loading icon also hangs in the center and does not advance.

Where should we look to correct this?

**Comment by ColdSphinX** [comment]
I have the same issue.
According to console:
> Uncaught TypeError: Cannot read property 'event' of undefined at receive (editor.js?v=060a1ff…:139)
This leads me to the following line of code:
`console.log('DrawIO Integration: Incorrect origin:' +msg.event);`
suggesting that this if clause is failing in addition to msg.event being undefined:
`if ( (evt.data.length > 0) && (evt.origin == OCA.Drawio.DURL) )`

**Comment by ColdSphinX** [comment]
The expected change I had to do with 0.8.7 (besides changing max-version to 12):

`--- js/editor.js	2017-05-23 12:23:02.556666666 +0200
+++ js/editor.js	2017-05-23 12:35:25.369999999 +0200
@@ -43,7 +43,7 @@
     OCA.DrawIO.EditFile = function (editWindow, filePath, origin) {
         var ncClient = OC.Files.getClient();
         var receiver = function (evt) {
-            if (evt.data.length > 0 && evt.origin === origin) {
+            if (evt.data.length > 0 && origin.includes(evt.origin)) {
                 var payload = JSON.parse(evt.data);
                 if (payload.event === "init") {
                     var loadMsg = OC.Notification.show(t(OCA.DrawIO.AppName, "Loading, please wait."));`

**Comment by ColdSphinX** [comment]
https://github.com/pawelrojek/nextcloud-drawio/pull/12
