### ISSUE TITLE
Files can't open with Firefox 69.x

### ISSUE THREAD

**Issue by chillriver** [pawelrojek/nextcloud-drawio#93]
In my Browser Firefox 69.x can't open draw.io files. The page shows "Page could not be loaded. Please try refreshing. Please ensure JavaScript is enabled." But Javascript is working fine and I Chromium instead can open files.

**Comment by davidjgraph** [comment]
Any errors in the browser console? Any extensions in FF that might be interfering?

**Comment by chillriver** [comment]
Webconsole of FF said:

```
TypeError: localStorage is null
    load https://www.draw.io/js/app.min.js:8705
    <anonym> https://www.draw.io/js/app.min.js:8709
```
```
ReferenceError: App is not defined
    <anonym> https://www.draw.io/?embed=1&offline=1&stealth=1&ui=kennedy&lang=de&spin=1&proto=json:457
```

**Comment by davidjgraph** [comment]
Do you have cookies disabled for that site?

**Comment by chillriver** [comment]
Yeah, that was the right tip. Now it works, thanks. I'm setting in privacy and security the cookies "block from third-party trackers" instead "block cookies from unvisited web sites" in FF.
