### ISSUE TITLE
on-premise draw.io

### ISSUE THREAD

**Issue by Jacq** [pawelrojek/nextcloud-drawio#98]
Is it possible to config the draw.io url, to use an on-premise draw.io instalation?
Regards,

**Comment by berendt** [comment]
@Jacq You can modify the `lib/appconfig.php` configuration file (https://github.com/pawelrojek/nextcloud-drawio/blob/master/drawio/lib/appconfig.php#L20).

But it'd be nice if it was properly configurable.

**Comment by Jacq** [comment]
Found it, changing there works.
It is also available in nextcloud web gui in "Configuration" => "Additional Config" (last menu at the very bottom) => draw.io section
Thanks!

**Comment by berendt** [comment]
@Jacq Thank you for pointing that out. I didn't find it in the settings.

I think the issue can be closed.
